### ISSUE TITLE
Updates containing a message with no parameters throws an exception

### ISSUE THREAD

**Issue by MartinSStewart** [layflags/elm-monitor#2]
Steps to reproduce:
1. Create a new project with elm-monitor hooked up
2. Add a button that sends off a message with no parameter (i.e. `NoOp`)
3. Notice that when you click the button the following error appears 
![image](https://user-images.githubusercontent.com/5068391/51804766-276ce500-2265-11e9-970e-18c44acac706.png)
4. Notice that if you add a parameter to your message (i.e. `NoOp Int`) the error no longer appears.

**Comment by layflags** [comment]
fixed in `elm-monitor@0.0.5`, thx @MartinSStewart 👍
